name: Metrics

on:
  schedule:
    - cron: "0 0 * * 0" # every Sunday
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.svg
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
